version: "3"

services:
  db:
    image: postgres
    container_name: dvd_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dvd_sample
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "/var/opt/postgres/dvd_sample/data:/var/lib/postgresql/data"